version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0

workflows:
  build:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/

      - orb-tools/pack:
          source-dir: src
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires: [orb-tools/lint]
          filters:
            tags:
              only: /.*/

      - orb-tools/publish:
          attach-workspace: true
          orb-path: workspace/packed/orb.yml
          orb-ref: theo/hello@dev:${CIRCLE_BRANCH}
          publish-token-variable: CIRCLECI_TOKEN
          requires: [orb-tools/pack]
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/

      - orb-tools/publish:
          attach-workspace: true
          orb-path: workspace/packed/orb.yml
          orb-ref: theo/hello@${CIRCLE_TAG##v}
          publish-token-variable: CIRCLECI_TOKEN
          requires: [orb-tools/pack]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
