version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0

workflows:
  build:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          source-dir: src
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires: [orb-tools/lint]

      - orb-tools/publish-dev:
          orb-name: theo/hello
          orb-path: workspace/packed/orb.yml
          publish-token-variable: CIRCLECI_TOKEN
          requires: [orb-tools/pack]

      - orb-tools/publish:
          attach-workspace: true
          orb-path: workspace/packed/orb.yml
          orb-ref: theo/hello@${CIRCLE_TAG}
          requires: [orb-tools/pack]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
